/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import basedatos.DataBase;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego V
 */
public class VentanaBaja extends javax.swing.JFrame {
JFrame ventana;
    /**
     * Creates new form VentanaBaja
     */
    public VentanaBaja(JFrame ventana) {
        initComponents();
        this.ventana = ventana;
        this.setLocationRelativeTo(null);
        this.botonBuscar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        botonBorrarTodo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textoExpediente = new javax.swing.JTextField();
        textoNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        textoTelefono = new javax.swing.JTextField();
        textoDireccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textoEdad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel4.setText("Dirección");

        botonBorrarTodo.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        botonBorrarTodo.setText("Limpiar campos");
        botonBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarTodoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel5.setText("Edad");

        textoExpediente.setToolTipText("");
        textoExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoExpedienteActionPerformed(evt);
            }
        });
        textoExpediente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoExpedienteKeyPressed(evt);
            }
        });

        textoNombre.setEditable(false);
        textoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jButton1.setText("Menú Principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textoTelefono.setEditable(false);
        textoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTelefonoActionPerformed(evt);
            }
        });

        textoDireccion.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel1.setText("Expediente");

        textoEdad.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Introduce el expediente del  alumno");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel3.setText("Teléfono");

        botonGuardar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        botonGuardar.setText("Dar de baja");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonBuscar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(botonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoTelefono)
                            .addComponent(textoExpediente)
                            .addComponent(textoNombre)
                            .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(botonGuardar)
                        .addGap(51, 51, 51)
                        .addComponent(botonBorrarTodo)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGuardar)
                    .addComponent(botonBorrarTodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(botonBuscar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarTodoActionPerformed
        // TODO add your handling code here:
        textoDireccion.setText("");
        textoEdad.setText("");
        textoExpediente.setText("");
        textoNombre.setText("");
        textoTelefono.setText("");
    }//GEN-LAST:event_botonBorrarTodoActionPerformed

    private void textoExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoExpedienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoExpedienteActionPerformed

    private void textoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreActionPerformed
        // TODO add your handling code here:       

    }//GEN-LAST:event_textoNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        VentanaPrincipal p = new VentanaPrincipal();
        p.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTelefonoActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:  

        DataBase conn = new DataBase();
        conn.cargarDriver();
        conn.conectar("localhost", "3306", "alumnos", "usuario", "usuario");

        PreparedStatement ps = null;
        try {
            ps = conn.prepararSentencia(
                    "DELETE FROM alumno WHERE expediente=?");
        } catch (SQLException ex) {
            Logger.getLogger(VentanaBaja.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ps.setString(1, textoExpediente.getText());

            // Ejecuto la inserción
            ps.executeUpdate();            
            JOptionPane.showMessageDialog(this, "Alumno borrado con éxito.");

        } catch (SQLException ex) {
            Logger.getLogger(VentanaAlta.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ha habido un error al borrar el alumno.");
        } finally {
            conn.desconectar();
        }


    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        DataBase conn = new DataBase();
        conn.cargarDriver();
        conn.conectar("localhost", "3306", "alumnos", "usuario", "usuario");

        String expedienteAlumno = textoExpediente.getText();
        if (expedienteAlumno.isEmpty() || expedienteAlumno.length() > 5) {
            JOptionPane.showMessageDialog(this, "El expediente del alumno no puede estar vacío y tiene que tener 5 caracteres como máximo.");
        } else {

            PreparedStatement ps = null;
            try {
                ps = conn.prepararSentencia("SELECT * FROM alumno WHERE expediente =?");
                ps.setString(1, textoExpediente.getText());
            } catch (SQLException ex) {
                Logger.getLogger(VentanaBaja.class.getName()).log(Level.SEVERE, null, ex);
            }
            ResultSet rs = null;
            try {
                rs = ps.executeQuery();
            } catch (SQLException ex) {
                Logger.getLogger(VentanaBaja.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {

                if (rs.next()) {
                    // Recojo los valores
                    String nombre = rs.getString(2);
                    String telefono = rs.getString(3);
                    String direccion = rs.getString(4);
                    String edad = rs.getString(5);

                    textoNombre.setText(nombre);
                    textoTelefono.setText(telefono);
                    textoDireccion.setText(direccion);
                    textoEdad.setText(edad);
                } else {                    
                    JOptionPane.showMessageDialog(this, "El expediente " + textoExpediente.getText() + " no existe.");
                    botonBorrarTodo.doClick();
                }
            } catch (SQLException ex) {
                Logger.getLogger(VentanaBaja.class.getName()).log(Level.SEVERE, null, ex);                
            } finally {
                conn.desconectar();
            }
        }

    }//GEN-LAST:event_botonBuscarActionPerformed

    private void textoExpedienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoExpedienteKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            botonBuscar.doClick();
        }
    }//GEN-LAST:event_textoExpedienteKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        ventana.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

  
    private void buscarAlumno(DataBase conn, String expediente) throws SQLException {

        // Obtengo el PreparedStatement
        PreparedStatement ps = conn.prepararSentencia(
                "SELECT Expediente FROM alumno WHERE expediente='?'");
        try {
            ps.setString(1, expediente);

            // Ejecuto la busqueda
            ps.executeUpdate();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "No existe ningún alumno con ese expediente.");

        } finally {
            conn.desconectar();
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrarTodo;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField textoDireccion;
    private javax.swing.JTextField textoEdad;
    private javax.swing.JTextField textoExpediente;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoTelefono;
    // End of variables declaration//GEN-END:variables
}
